// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://totmrzrkkkhwwzjxzutc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvdG1yenJra2tod3d6anh6dXRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3OTcwMzUsImV4cCI6MjA2MjM3MzAzNX0.yiw1-QdlCylaMV5OUiWkEOsiTMgo_FkdqRXsx9mel3k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);